<a href="https://colab.research.google.com/github/NandiniBasdwar7/concise/blob/main/daya6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# NumPy for Aggregation and Transformation
#1)np.mean-to calculate the average of an array (ndarray).
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)


print(np.mean(a))


print(np.mean(a, axis=0))


print(np.mean(a, axis=1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]


In [ ]:
#np.sum() - calculate the sum of an array (ndarray).
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)


print(np.sum(a))


print(np.sum(a, axis=0))


print(np.sum(a, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]


In [ ]:
#np.std- function is used to calculate the standard deviation along a specified axis of an array
import numpy as np

data = [4, 8, 15, 16, 23, 42]
stddev = np.std(data)
print("Standard Deviation:", stddev)

Standard Deviation: 12.315302134607444


In [ ]:
#Boolean indexing, conditional replacement
#In NumPy, boolean indexing allows us to filter elements from an array based on a specific condition.

import numpy as np

arr = np.array([1, 5, 2, 8, 3, 6])

arr[arr > 5] = 0
print(arr)


# create an array of numbers
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# create a boolean mask
boolean_mask = array1 % 2 != 0

# boolean indexing to filter the odd numbers
result = array1[boolean_mask]

print(result)



[1 5 2 0 3 0]
[1 3 5 7 9]


In [ ]:
#conditional replacement-It takes three arguments: condition, x, and y.
#condition: A boolean array or condition that evaluates to a boolean array.
#x: The value to use where the condition is True.
#y: The value to use where the condition is False.
#If x and y are arrays, they must be broadcastable to the shape of the condition.
import numpy as np

arr = np.array([1, 5, 2, 8, 3, 6])
# Replace elements greater than 5 with 0, otherwise keep the original value
modified_arr = np.where(arr > 5, 0, arr)
print(modified_arr)


# Replace elements greater than 5 with 10, and elements less than or equal to 5 with -1
modified_arr_complex = np.where(arr > 5, 10, -1)
print(modified_arr_complex)


[1 5 2 0 3 0]
[-1 -1 -1 10 -1 10]


In [ ]:
#Given a 2D NumPy array of daily sensor data (rows: days, cols: sensors):
#Compute the average per sensor.
#Find the day with maximum total reading.
import numpy as np
data=np.random.randint(10,100,size=(7,4))
print(data)

average_per_sensor=np.mean(data,axis=0)
print(average_per_sensor)

max_total_reading=np.argmax(np.sum(data,axis=1))
print(max_total_reading)


[[72 50 29 51]
 [81 89 73 20]
 [94 88 71 31]
 [61 41 97 87]
 [27 81 95 26]
 [11 84 34 87]
 [16 58 78 70]]
[51.71428571 70.14285714 68.14285714 53.14285714]
3


In [6]:
import numpy as np

    # Assuming 'data.csv' contains numerical data separated by commas
data_array = np.genfromtxt('/content/data.csv',  delimiter=',')
print(data_array)

[[    nan     nan     nan ...     nan     nan     nan]
 [-0.4394 -0.093   0.1718 ...  0.5898 -0.4872     nan]
 [-0.4348 -0.1198  0.2474 ...  0.4546 -0.091      nan]
 ...
 [-0.6696 -0.373   0.1584 ...  0.0728 -0.5818     nan]
 [-0.5764 -0.1764  0.5106 ... -0.0434 -0.5        nan]
 [-0.6624 -0.3334  0.3666 ... -0.1708 -0.317      nan]]


In [8]:
#Memory-efficient transformations
#1)use in-place operations- avoid making new arrays
import numpy as np
arr=np.array([1,2,3,4])
arr *= 2
print(arr)

[2 4 6 8]


In [9]:
#use smaller data types
import numpy as np
arr=np.array([1,2,3,4],dtype=np.int8)
print(arr)

[1 2 3 4]


In [10]:
#use views and copies
arr=np.array([1,2,3,4])
view_arr=arr.view()
copy_arr=arr.copy()
print(view_arr)
print(copy_arr)

[1 2 3 4]
[1 2 3 4]


In [ ]:
#avoid unnecessary intermediate arrays
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
result=np.add(arr1,arr2)
print(result)

In [24]:
#Create a data generator that outputs daily sensor data
import numpy as np
import datetime
def generator_data(days=7,sensors=4,seed=42):
  np.random.seed(seed)
  data=np.random.randint(10,100,size=(days,sensors))
  start_date=datetime.datetime.now()
  dates=[start_date + datetime.timedelta(days=i) for i in range(days)]
  for i in range(days):
    print(dates[i],data[i])
    return np.array(dates),data

dates,sensors_data=generator_data()
for i in range(len(dates)):
  print(dates[i],sensors_data[i])

2025-07-14 14:04:03.182742 [61 24 81 70]
2025-07-14 14:04:03.182742 [61 24 81 70]
2025-07-15 14:04:03.182742 [30 92 96 84]
2025-07-16 14:04:03.182742 [84 97 33 12]
2025-07-17 14:04:03.182742 [31 62 11 97]
2025-07-18 14:04:03.182742 [39 47 11 73]
2025-07-19 14:04:03.182742 [69 30 42 85]
2025-07-20 14:04:03.182742 [67 31 98 58]


In [27]:
#Exercise 10:
#Simulate one week of hourly power consumption data:
#7x24 matrix.
#Calculate total, average, and variance per day.

import numpy as np
data=np.random.randint(100,500,(7,24))
print('total',np.sum(data,axis=1))
print('average',np.mean(data,axis=1))
print('variance',np.var(data,axis=1))


total [6687 7723 7647 7187 7656 6614 7182]
average [278.625      321.79166667 318.625      299.45833333 319.
 275.58333333 299.25      ]
variance [11469.90104167 12867.33159722 13982.31770833 14665.99826389
 11110.5        11371.74305556 12457.52083333]
